/**
* @author  Walid Abbassi
*/
package com.opendevup.scolarite.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

//This tells Hibernate to make a table out of this class
@Entity
@Table(name = "etudiant")
public class Etudiant implements Serializable{
	
	// ------------------------
	// PRIVATE FIELDS
	// ------------------------
	
	// An autogenerated id (unique for each Etudiant in the db)
	@Id //JPA
	@GeneratedValue //JPA
	private Long id;
	
	// Field not null (with name NAME and length [optional})
	@NotNull
	@NotEmpty
	@Size(min=3,max=30)
	@Column(name="NAME",length=30)
	private String nom;
	@NotNull
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date dateNaissance;
	@NotNull
	@NotEmpty
	@Email
	private String email;
	private String photo;
	
	// ------------------------
	// PUBLIC METHODS
	// ------------------------
	
	// constructor For JPA
	public Etudiant() {
		super();
	}
	
	// constructor using Field
	public Etudiant(String nom, Date dateNaissance, String email,
			String photo) {
		super();
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.email = email;
		this.photo = photo;
	}
	
	// Getter and setter methods
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getNom() {
		return nom;
	}
	public void setNom(String nom) {
		this.nom = nom;
	}
	public Date getDateNaissance() {
		return dateNaissance;
	}
	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPhoto() {
		return photo;
	}
	public void setPhoto(String photo) {
		this.photo = photo;
	}
	

}// class Etudiant
